apiVersion: v1
kind: ConfigMap
metadata:
  name: eli-maor-config
  labels:
    app: eli-maor
data:
  DEBUG: "False"
  ENVIRONMENT: "production"
  CORS_ORIGINS: '["https://yourdomain.com", "https://www.yourdomain.com"]'
